[package]
name = "steward"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing-subscriber = { version="0.3", features = ["env-filter"] }
serde = { version = "^1.0.133", features = ["derive"] }
tokio = { version = "^1.15.0", features = ["full"] }
tracing = "^0.1.29"
axum = "^0.4.3"

[dev-dependencies]
hyper = { version = "0.14", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
