[package]
name = "steward"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
der = { git = "https://github.com/RustCrypto/formats", features = ["std"] }
pkcs8 = { git = "https://github.com/RustCrypto/formats" }
sec1 = { git = "https://github.com/RustCrypto/formats" }
spki = { git = "https://github.com/RustCrypto/formats" }
x509 = { git = "https://github.com/RustCrypto/formats", features = ["std"] }
p256 = { version = "^0.10.1" }
ecdsa = { version = "^0.13.4" }
elliptic-curve = { version = "^0.11.12" }
zeroize = { version = "^1.5.2", features = ["alloc"] }

axum = { version = "^0.4.3", features = ["headers"] }
clap = { version = "^3.0.14", features = ["derive"] }
displaydoc = "^0.2.3"
hyper = { version = "^0.14.17", features = ["full"] }
mime = "^0.3.16"
thiserror = "^1.0.30"
tokio = { version = "^1.15.0", features = ["full"] }
tracing = "^0.1.29"
tracing-subscriber = { version="^0.3.8", features = ["env-filter"] }

[dev-dependencies]
tower = { version = "^0.4.11", features = ["util"] }
http = "^0.2.6"
rand = "^0.8.4"
