[sources]
allow-git = [
    "https://github.com/npmccallum/formats.git",
]

[licenses]
allow-osi-fsf-free = "neither"
confidence-threshold = 0.8
unlicensed = "deny"
copyleft = "deny"
default = "deny"
allow = [
    "ISC",
    "MIT",
    "OpenSSL",
    "AGPL-3.0",
    "Apache-2.0",
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]
