[licenses]
allow-osi-fsf-free = "neither"
confidence-threshold = 0.8
unlicensed = "deny"
copyleft = "deny"
default = "deny"
allow = [
    "MIT",
    "AGPL-3.0",
    "Apache-2.0",
    "BSD-3-Clause",
]
